name: Flagship-version
# This workflow is triggered on pushes to the repository.
on:
  push:
  workflow_call:

jobs:
  build:
    name: Install CLI
    runs-on: ubuntu-latest
    steps:
      - name: Install the CLI
        run: wget -qO- https://raw.githubusercontent.com/flagship-io/flagship/main/install.sh | bash

      - name: Run version
        run: flagship version

      - name: Configure CLI
        run: flagship configure --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }} --account-id c0n48jn5thv01k0ijmng --account-environment-id c0n48jn5thv01k0ijmo0

      - name: Create Project
        run: flagship project create -n "alive actions"
